#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
  # FOR ruby/rails: ripper-tags --tag-relative -R -f"$dir/$$.tags" --exclude=vendor,bin,script,public,tmp,db,node_modules
mv "$dir/$$.tags" "$dir/tags"

